---
title: "Tom Hardwicke"
position: "Research Fellow"
university: "University of Amsterdam"
image: ""
links:
  - label: '`r fontawesome::fa("twitter")`'
    url: "https://twitter.com/Tom_Hardwicke"
  - label: '`r fontawesome::fa("github")`'
    url: "https://github.com/TomHardwicke"
  - label: '<i class="ai ai-osf"></i>'
    url: "https://osf.io/i8w73/"
  - label: '<i class="ai ai-google-scholar"></i>'
    url: "https://scholar.google.co.uk/citations?user=1zq46yYAAAAJ&hl=en"
  - label: '`r fontawesome::fa("orcid")`'
    url: "https://orcid.org/0000-0001-9485-4952"
  - label: '`r fontawesome::fa("envelope")`'
    url: "mailto:hardwickete@gmail.com"
site: distill::distill_website
output:
  postcards::trestles_mod
---
 
## Publications

[[2022]] [[2021]] [[2020]] [[2019]] [[2018]] [[2017]] [[2016]] [[Before 2016](#pre-2016)]

#### Submitted

Hardwicke, T. E., Salholz-Hillel, M., Malički, M., Szűcs, D., Bendixen, T., Ioannidis, J. P. A. (preprint). Statistical guidance to authors at top-ranked journals across scientific disciplines. *MetaArXiv*.  
[[preprint]](https://doi.org/10.31222/osf.io/q6ajt) [[preregistration]](https://osf.io/cz9g3/) [[data]](https://dx.doi.org/10.17605/OSF.IO/JRX7D) [[materials]](https://dx.doi.org/10.17605/OSF.IO/JRX7D) [[analysis-code]](https://dx.doi.org/10.17605/OSF.IO/JRX7D) [[reproducible-container]](https://doi.org/10.24433/CO.6131540.v1)

Fernández, L. M., Hardwicke, T. E., & Vadillo, M. A. (preprint). Retracted papers clinging on to life: An observational study of post-retraction citations in psychology. *PsyArXiv*.  
[[preprint]](https://doi.org/hcht) [[data]](https://osf.io/t73rk/) [[analysis-code]](https://osf.io/t73rk/)

Hardwicke, T. E., & Wagenmakers, E.-J. (preprint). Reducing bias, increasing transparency, and calibrating confidence with preregistration. *MetaArXiv*.  
[[preprint]](https://doi.org/10.31222/osf.io/d7bcu)

#### 2022

Hardwicke, T. E., Thibault, R. T., Kosie, J. E., Tzavella, L., Bendixen, T., Handcock, S. A. Köneke, V. E., Ioannidis, J. P. A. (in press). Post-publication critique at top-ranked journals across scientific disciplines: A cross-sectional assessment of policies and practice. *Royal Society Open Science*.  
[[preprint]](https://doi.org/hc7d) [[preregistration]](https://osf.io/hjvnw/) [[data]](https://osf.io/8b6jy/) [[materials]](https://osf.io/8b6jy/) [[analysis-code]](https://osf.io/8b6jy/) [[reproducible-container]](https://doi.org/10.24433/CO.3805142.v1)

TARG Meta-Research Group & Collaborators [Thibault, R. T., Hardwicke, T. E., Clark, R. W. A., Pennington, C. R., Nilsonne, G., O'Mahony, A., Drax, K., Thompson, J., Munafò, M. R.] (2022). Discrepancy review: A feasibility study of a novel peer review intervention to reduce undisclosed discrepancies between registrations and publications. *Royal Society Open Science*, *9*, 220142.  
[[paper]](https://doi.org/10.1098/rsos.220142) [[preprint]](https://doi.org/hdgv) [[preregistration]](https://osf.io/w3bkt/) [[data]](https://osf.io/25ebk/) [[materials]](https://osf.io/5dh47/files) [[analysis-code]](https://osf.io/25ebk/) [[reproducible-container]](https://doi.org/10.24433/CO.9942414.v1)

Nosek, B. A., Hardwicke, T. E., Moshontz, H., Allard, A., Corker, K. S., Dreber, A., Fidler, F., Hilgard, J., Kline Struhl, M., Nuijten, M., Rohrer, J., Romero, F., Scheel., A., Scherer, L., Schönbrodt, F., & Vazire, S. (2022). Replicability, robustness, and reproducibility in psychological science. *Annual Review of Psychology*, *73*, 719-748.  
[[paper]](http://www.annualreviews.org/eprint/BEG4HHRDH6R6UHSGU3YR/full/10.1146/annurev-psych-020821-114157) [[preprint]](https://doi.org/ftzw) [[preregistration]](https://osf.io/7np92/) [[materials]](https://osf.io/7np92/) [[data]](https://osf.io/7np92/) [[analysis-code]](https://osf.io/7np92/) [[reproducible-container]](https://doi.org/10.24433/CO.4977248.v1)

Hardwicke, T. E., Thibault, R. T., Kosie, J. E., Wallach, J. D., Kidwell, M. C., & Ioannidis, J. P. A. (2022). Estimating the prevalence of transparency and reproducibility-related research practices in psychology (2014-2017). *Perspectives on Psychological Science*, *17*(1), 239-251.  
[[paper]](https://doi.org/10.1177%2F1745691620979806) [[preprint]](https://doi.org/10.31222/osf.io/9sz2y) [[preregistration]](https://osf.io/q96eh/) [[materials]](https://osf.io/c89sy/) [[data]](https://osf.io/5qmz7/) [[analysis-code]](https://osf.io/gfjtq/) [[reproducible-container]](https://doi.org/10.24433/CO.1618143.v2)

#### 2021

Hardwicke, T. E., Szucs D., Thibault, R. T., Crüwell, S., van den Akker, O. R., Nuijten, M. B., & Ioannidis, J. P. A. (2021). Citation patterns following a strongly contradictory replication result: Four case studies from psychology. *Advances in Methods and Practices in Psychological Science*, *4*, 1-14.  
[[paper]](https://doi.org/10.1177/25152459211040837) [[preprint]](https://doi.org/ftx5) [[preregistration]](https://osf.io/eh5qd/) [[materials]](https://osf.io/w8h2q/) [[data]](https://osf.io/w8h2q/) [[analysis-code]](https://osf.io/w8h2q/) [[reproducible-container]](https://doi.org/10.24433/CO.4225975.v3)

Hardwicke, T. E., Bohn, M., MacDonald, K., Hembacher, E., Nuijten, M. B., Peloquin, B. N., deMayo, B., Long, B., Yoon, E. J., & Frank, M. C. (2021). Analytic reproducibility in articles receiving open data badges at the journal Psychological Science: An observational study. *Royal Society Open Science*, *8*, 201494.  
[[paper]](https://doi.org/fp2m) [[preprint]](https://doi.org/d3mz) [[preregistration]](https://osf.io/2cnkq/) [[materials]](https://osf.io/wy6a5/) [[data]](https://osf.io/tfd8z/) [[analysis-code]](https://osf.io/tfd8z/) [[reproducible-container]](https://doi.org/10.24433/CO.1796004.v3)

#### 2020

Hardwicke, T. E., & Goodman, S. N. (2020). How often do leading biomedical journals use statistical experts to evaluate statistical methods? The results of a survey. *PLOS ONE*, *15*, e0239598.  
[[paper]](https://dx.doi.org/10.1371%2Fjournal.pone.0239598) [[preprint]](https://doi.org/10.31222/osf.io/z27u4) [[materials]](https://doi.org/10.17605/osf.io/p7g8w) [[data]](https://doi.org/10.17605/osf.io/nscv3) [[analysis-code]](https://doi.org/10.17605/osf.io/dy6kj) [[reproducible-container]](https://doi.org/10.24433/CO.3883021.v1)

Hardwicke, T. E., Serghiou, S., Janiaud, P., Danchev, V., Crüwell, S., Goodman, S. N., & Ioannidis, J. P. A. (2020). Calibrating the scientific ecosystem through meta-research. *Annual Review of Statistics and its Application*, *7*, 11-37.  
[[paper]](https://doi.org/10.1146/annurev-statistics-031219-041104) [[preprint]](https://doi.org/10.31222/osf.io/krb58)

Ferrero, M., Hardwicke, T. E., Konstantinidis, E., & Vadillo, M. A. (2020). The effectiveness of refutation texts to correct misconceptions among educators. *Journal of Experimental Psychology: Applied*, *26*, 411-421.  
[[paper]](https://psycnet.apa.org/doi/10.1037/xap0000258) [[preprint]](https://doi.org/10.31234/osf.io/ehybj) [[materials]](https://osf.io/73a9y/) [[data]](https://osf.io/sg6jy/) [[analysis-code]](https://osf.io/pxv5b/)

Hardwicke, T. E., Wallach, J. D., Kidwell, M. C., Bendixen, T., Crüwell, S., & Ioannidis, J. P. A. (2020). An empirical assessment of transparency and reproducibility-related research practices in the social sciences (2014-2017). *Royal Society Open Science*, *7*, 190806.  
[[paper]](https://dx.doi.org/10.1098/rsos.190806)
[[preprint]](https://doi.org/10.31222/osf.io/6uhg5) [[preregistration]](https://osf.io/u5bk9/) [[materials]](https://osf.io/z9qtr/) [[data]](https://osf.io/u9fw8/) [[analysis-code]](https://osf.io/sbrez/) [[reproducible-container]](https://doi.org/10.24433/CO.2749769.v2)

#### 2019

Hardwicke, T. E., & Ioannidis, J. P. A. (2019). Petitions in scientific argumentation: dissecting the request to retire statistical significance. *European Journal of Clinical Investigation*, *49*, e13162.  
[[paper]](https://doi.org/10.1111/eci.13162) [[preprint]](https://doi.org/10.31222/osf.io/73xm5) [[preregistration]](https://osf.io/hbkj3/) [[materials]](https://osf.io/u7nx4/) [[data]](https://osf.io/6a94k/) [[analysis-code]](https://osf.io/jpztm/) [[reproducible-container]](https://doi.org/10.24433/CO.3912558.v1) [[comment1]](https://doi.org/10.1111/eci.13165) [[comment2]](https://doi.org/10.1111/eci.13170) [[comment3]](https://doi.org/10.1111/eci.13176)

Nosek, B. A., Beck, E. D., Campbell, L., Flake, J. K., Hardwicke, T. E., Mellor, D. T., van ‘t Veer, A. E., & Vazire, S. (2019). Preregistration is hard, and worthwhile. *Trends in Cognitive Sciences*, *23*, 815-818.  
[[paper]](https://doi.org/10.1016/j.tics.2019.07.009) [[preprint]](https://doi.org/10.31234/osf.io/wu3vs)

Hardwicke, T. E., Frank, M. C., Vazire, S., & Goodman, S. N. (2019). Should psychology journals adopt specialized statistical review? *Advances in Methods and Practices in Psychological Science*, *2*, 240-249.  
[[paper]](https://doi.org/10.1177/2515245919858428) [[materials]](https://osf.io/tmah8/files/) [[data]](https://osf.io/nquws/files/) [[analysis-code]](https://osf.io/4zurk/files/) [[reproducible-container]](https://doi.org/10.24433/CO.8241121.v3) [[media]](https://www.psychologicalscience.org/publications/observer/obsonline/strengthening-psychological-science-with-specialized-statistical-review.html?utm_source=tw&utm_medium=social&utm_campaign=AMPPSstatisticalreview)

#### 2018

Hardwicke, T. E. & Ioannidis, J. P. A. (2018). Mapping the universe of registered reports. *Nature Human Behaviour*, *2*, 793–796.  
[[paper]](https://rdcu.be/8eBP) [[materials]](https://osf.io/uzegq/) [[data]](https://osf.io/rv7eb/) [[analysis-code]](https://osf.io/uzfjp/) [[reproducible-container]](https://doi.org/10.24433/CO.03fa2564-3910-4982-9882-4f2fcec50385.v3) [[preprint]](https://dx.doi.org/10.17605/OSF.IO/FZPCY) [[comment]](https://doi.org/10.1038/s41562-018-0449-6) [[comment2]](https://doi.org/10.1038/s41562-018-0477-2)

Hardwicke, T. E., Mathur, M. B., MacDonald, K., Nilsonne, G., Banks, G. C., Kidwell, M. C., Hofelich Mohr, A., Clayton, E., Yoon, E. J., Henry Tessler, M., Lenne, R. L., Altman, S., Long, B., & Frank, M. C. (2018). Data availability, reusability, and analytic reproducibility: Evaluating the impact of a mandatory open data policy at the journal Cognition. *Royal Society Open Science*, *5*, 180448.  
[[paper]](https://dx.doi.org/10.1098/rsos.180448) [[preprint]](https://dx.doi.org/10.17605/OSF.IO/39CFB) [[preregistration]](https://osf.io/q4qy3/) [[materials]](https://osf.io/k2mdr/) [[data]](https://osf.io/6s8b3/) [[analysis-code]](https://osf.io/wf3as/) [[reproducible-container]](https://doi.org/10.24433/CO.abd8b483-c5e3-4382-a493-1fc5aecb0f1d.v2)  [[blog1]](https://tomhardwicke.netlify.app/blog/psychology-reproducibility/) [[blog2]](https://tomhardwicke.netlify.app/blog/open-data-reusability/) [[comment]](https://doi.org/10.1016/j.cognition.2018.10.008)

Hardwicke, T. E. & Ioannidis, J. P. A. (2018). Populating the Data Ark: An attempt to retrieve, preserve, and liberate data from the most highly-cited psychology and psychiatry articles. *PLOS ONE*, *13*, e0201856.  
[[paper]](https://doi.org/10.1371/journal.pone.0201856) [[materials]](https://osf.io/4dum6/) [[data]](https://osf.io/r38qu/) [[analysis-code]](https://osf.io/7syrt/) [[reproducible-container]](https://doi.org/10.24433/CO.241ffbb1-5b81-44bd-94f4-d066b62c5f7f.v2) [[blog]](https://tomhardwicke.netlify.app/blog/attrition-scholarly-record/) [[media]](https://blogs.discovermagazine.com/neuroskeptic/2018/08/06/how-accessible-is-psychology-data/)

Hardwicke, T. E., Henry Tessler, M., Peloquin, B., & Frank, M. C. (2018). A Bayesian decision-making framework for replication. *Behavioral and Brain Sciences*, *41*, e132.  
[[paper]](https://doi.org/10.1017/S0140525X18000675) [[preprint]](https://dx.doi.org/10.17605/OSF.IO/N3YAH)

Klein, O., Hardwicke, T. E., Aust, F., Breuer, J., Danielsson, H., Hofelich Mohr, A., IJzerman, H., Nilsonne, G., Vanpaemel, W., & Frank, M. C. (2018). A practical guide for transparency in psychological science. *Collabra: Psychology*, *4*, 20.  
[[paper]](https://doi.org/10.1525/collabra.158) [[materials]](https://osf.io/xf6ug/)

#### 2017

Cristea, I. A., Naudet, F., Shanks, D. R., & Hardwicke, T. E. (2017). Post-retrieval Tetris should not be likened to a ‘cognitive vaccine’. *Molecular Psychiatry*, *23*, 1972-1973.  
[[paper]](https://dx.doi.org/10.1038/mp.2017.222) [[pdf]](files/Cristea_tetris_2017.pdf) [[data]](https://osf.io/nwz9j/) [[analysis-code]](https://osf.io/p3z58/)

#### 2016

Kidwell, M. C., Lazarević, L. B., Baranski, E., Hardwicke, T. E., Piechowski, S., Falkenberg, L-S., Kennett, C., Slowik, A., Sonnleitner, C., Hess-Holden, C., Errington, T. M., Fiedler, S., & Nosek, B. A. (2016). Badges to acknowledge open practices: A simple, low cost, effective method for increasing transparency. *PLOS Biology*, *14*, e1002456.  
[[paper]](https://dx.doi.org/10.1371/journal.pbio.1002456) [[preregistration]](https://osf.io/3upzh/) [[materials]](https://osf.io/8kt4b/) [[data]](https://osf.io/u6g7t/) [[analysis-code]](https://osf.io/257kv/)

Hardwicke, T. E. & Shanks, D. R. (2016). Reply to Walker and Stickgold: Proposed boundary conditions on memory reconsolidation will require empirical verification. *PNAS*, *113*, E3993-E3994.  
[[paper]](https://dx.doi.org/10.1073/pnas.1608235113) [[pdf]](files/sequenceReconReply.pdf)

Hardwicke, T. E., Mahdi, T., & Shanks, D. R. (2016). Post-retrieval new learning does not reliably induce human memory updating via reconsolidation. *PNAS*, *113*, 5206-5211.  
[[paper]](https://dx.doi.org/10.1073/pnas.1601440113) [[pdf]](files/sequenceRecon.pdf) [[materials]](https://osf.io/xyf34/) [[data]](https://osf.io/bm47u/) [[analysis-code]](https://osf.io/se6gb/) [[comment]](https://doi.org/10.1073/pnas.1607964113) [[media]](https://blogs.discovermagazine.com/neuroskeptic/2016/05/19/does-reconsolidation-exist/)

Vadillo, M. A., Hardwicke, T. E., & Shanks, D. R. (2016). Selection bias, vote counting, and money priming effects: A comment on Rohrer, Pashler, and Harris (2015) and Vohs (2015). *Journal of Experimental Psychology: General*, *145*, 655-663.  
[[paper]](https://dx.doi.org/10.1037/xge0000157) [[pdf]](files/moneyPriming.pdf) [[data]](https://osf.io/4e3gy/) [[media]](https://blogs.discovermagazine.com/neuroskeptic/2016/04/23/publication-bias-in-money-priming/)

Hardwicke, T. E. (2016). Persistence and plasticity in the human memory system: An empirical investigation of the overwriting hypothesis. *PhD Thesis*.  
[[thesis]](https://dx.doi.org/10.17605/OSF.IO/R4C32) [[data]](https://osf.io/rxtgs/) [[analysis-code]](https://osf.io/rxtgs/) [[osf]](https://osf.io/rxtgs/)

#### Before 2016 {#pre-2016}

Baker, R., Dexter, M., Hardwicke, T. E., Goldstone, A., & Kourtzi, Z. (2014). Learning to predict: Exposure to temporal sequences facilitates prediction of future events. *Vision Research*, *99*, 124-133.  
[[paper]](https://dx.doi.org/10.1016/j.visres.2013.10.017) [[pdf]](files/learningToPredict.pdf)

Ludwig, C. J. H., Farrell, S., Ellis, L. A., Hardwicke, T. E., & Gilchrist, I. D. (2012). Context-gated statistical learning and its role in visual-saccadic decisions. *Journal of Experimental Psychology: General*, *141*, 150-169.  
[[paper]](https://dx.doi.org/10.1037/a0024916) [[pdf]](files/contextGatedSL.pdf)

Hardwicke, T. E., Jameel, L., Jones, M., Walczak, E. J., & Magis-Weinberg, L. (2014). Only human: Scientists, systems, and suspect statistics. *Opticon1826*, *16*, 1-12.  
[[paper]](https://dx.doi.org/10.5334/opt.ch) [[pdf]](files/onlyHuman.pdf)

Hardwicke, T. E. (2012). Biological Psychology. *Psychology Learning & Teaching*, *11*, 112-113.  
[[paper]](https://dx.doi.org/10.2304/plat.2012.11.1.106)
